ecs/elections/urls.py
from django.conf.urls import url

from ecs.elections.views import *

urlpatterns = [
    url(r'^list/$', ElectionListView.as_view(), name='election_list'),
    url(r'^new/$', ElectionCreateView.as_view(), name='election_create'),
    url(r'^delete/(?P<pk>\d+)/$', ElectionDeleteView.as_view(), name='election_delete'),
    url(r'^details/(?P<pk>\d+)/$', ElectionDetailView.as_view(), name='election_details'),
    url(r'^load_data/(?P<pk>\d+)/$', ElectionLoadDataFormView.as_view(), name='election_load_data'),
    url(r'^generate_data/(?P<pk>\d+)/$', ElectionGenerateDataFormView.as_view(), name='election_generate'),
    url(r'^paint/(?P<pk>\d+)/$', ElectionPaintView.as_view(), name='election_paint'),
    url(r'^chart_data/(?P<pk>\d+)/$', ElectionChartView.as_view(), name='chart_data'),
    url(r'^add_result/(?P<pk>\d+)/$', ResultCreateView.as_view(), name='result_create'),
    url(r'^result/(?P<pk>\d+)/$', ResultDetailsView.as_view(), name='result_details'),
    url(r'^result/(?P<pk>\d+)/delete/$', ResultDeleteView.as_view(), name='result_delete'),
    url(r'^chart_data/result/(?P<pk>\d+)/$', ResultChartView.as_view(), name='result_chart_data'),
    url(r'^algorithms_chart_data/(?P<pk>\d+)/$', AlgorithmsChartView.as_view(), name='algorithms_chart_data'),
]

ecs/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ecs.accounts.urls', namespace='accounts')),
    url(r'^elections/', include('ecs.elections.urls', namespace='elections')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

ecs/elections/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.forms.models import model_to_dict

from ecs.geo.models import Point
from ecs.utils.math import ell_p_norm


class Election(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=150)
    committee_size = models.PositiveIntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('elections:election_details', args=(self.pk,))

    def is_set_up(self):
        """
        Indicates if candidates and voters were added to election.
        """
        if self.candidates.all() and self.voters.all():
            return True
        else:
            return False

    def is_generated(self):
        """
        Indicates if elections were
        generated from normal distribution.
        """
        try:
            if self.candidates.all()[0].position:
                return True
            else:
                return False
        except:
            return False


class Candidate(models.Model):
    name = models.CharField(max_length=50, null=True)
    position = models.ForeignKey(Point, null=True)
    preferences = models.ManyToManyField('Voter', through='Preference')
    election = models.ForeignKey(Election, related_name='candidates')
    soc_id = models.IntegerField(null=True)

    def __unicode__(self):
        return self.name


class Voter(models.Model):
    repeats = models.IntegerField(default=1)
    position = models.ForeignKey(Point, null=True)
    election = models.ForeignKey(Election, related_name='voters')

    def set_preferences_by_ids(self, ids):
        preferences = []
        for preference, candidate_id in enumerate(ids):
            preferences.append(Preference(
                candidate=Candidate.objects.get(election=self.election, soc_id=candidate_id),
                voter=self,
                preference=preference + 1
            ))
        Preference.objects.bulk_create(preferences)

    def calculate_committee_score(self, committee, p, candidates_number):
        """
        Calculate committee score multiplied by vote repeats

        :param candidates_number: number of candidates in election
        :type candidates_number: int
        :type committee: list of ecs.elections.models.Candidate
        :type p: int
        :rtype: Decimal
        :return: committee score
        """
        # create pos_v sequence, but order actually
        # does not matter in our election system:
        voter_preferences = self.preferences.filter(candidate__in=committee).values_list('preference', flat=True)
        voter_preferences = [candidates_number - x for x in voter_preferences]
        return self.repeats * ell_p_norm(voter_preferences, p)


class Preference(models.Model):
    class Meta:
        ordering = ['preference']

    candidate = models.ForeignKey(Candidate)
    voter = models.ForeignKey(Voter, related_name='preferences')
    preference = models.IntegerField(null=False)


BRUTE_ALGORITHM = 'b'
GENETIC_ALGORITHM = 'g'
GREEDY_ALGORITHM = 'r'
GREEDY_CC = 'c'
ALGORITHM_CHOICES = (
    (BRUTE_ALGORITHM, 'Brute force'),
    (GENETIC_ALGORITHM, 'Genetic'),
    (GREEDY_ALGORITHM, 'Greedy Algorithm'),
    (GREEDY_CC, 'Greedy CC'),
)


class Result(models.Model):
    class Meta:
        ordering = ['p_parameter']

    election = models.ForeignKey(Election, related_name='results')
    p_parameter = models.PositiveIntegerField()
    winners = models.ManyToManyField(Candidate)
    algorithm = models.CharField(choices=ALGORITHM_CHOICES, max_length=1)
    time = models.FloatField(null=True)
    score = models.FloatField(null=True)

    def calculate_score(self):
        score = 0
        for voter in self.election.voters.all():
            score += voter.calculate_committee_score(
                self.winners.all(),
                self.p_parameter,
                self.election.candidates.count()
            )
        return score

    def get_absolute_url(self):
        return reverse('elections:result_details', args=(self.pk,))

    def __unicode__(self):
        return u'Result of {} with p={}'.format(
            self.election, self.p_parameter
        )


class GeneticAlgorithmSettings(models.Model):
    result = models.OneToOneField(Result)
    mutation_probability = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=10,
    )
    crossing_probability = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=20,
    )
    cycles = models.IntegerField(
        validators=[MinValueValidator(0)],
        default=50,
    )

ecs/elections/views.py
import json

from django.contrib import messages
from django.core.urlresolvers import reverse_lazy, reverse
from django.db import transaction
from django.forms.widgets import Select
from django.http.response import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import CreateView, FormView

from ecs import settings
from ecs.elections.algorithms.brute_force import BruteForce
from ecs.elections.algorithms.genetic import GeneticAlgorithm
from ecs.elections.algorithms.greedy_algorithm import GreedyAlgorithm
from ecs.elections.algorithms.greedy_cc import GreedyCC
from ecs.elections.election_generator import ElectionGenerator
from ecs.elections.election_paint_loader import ElectionPaintLoader
from ecs.elections.exceptions import CandidatesNameIncorrectFormatException, SummingLineTypeException, \
    BadDataFormatException, PreferenceOrderTypeException, PreferenceOrderLogicException
from ecs.elections.exceptions import IncorrectTypeOfCandidatesNumberException, SummingLineFormatException
from ecs.elections.forms import ElectionForm, ElectionLoadDataForm, ElectionGenerateDataForm, ResultForm, \
    GeneticAlgorithmForm
from ecs.elections.helpers import check_votes_number_unique_votes_relation, check_vote_consistency, \
    check_number_of_votes_consistency
from ecs.elections.models import Election, Candidate, Voter, BRUTE_ALGORITHM, Result, GENETIC_ALGORITHM
from ecs.elections.models import GREEDY_ALGORITHM, GREEDY_CC
from ecs.geo.models import Point
from ecs.utils.chart_views import ChartMixin
from ecs.utils.views import LoginRequiredMixin


class ElectionListView(LoginRequiredMixin, ListView):
    model = Election
    template_name = 'election_list.html'
    context_object_name = 'elections'
    active_election_list = 'active'

    def get_queryset(self):
        qs = super(ElectionListView, self).get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs


class ElectionCreateView(LoginRequiredMixin, CreateView):
    form_class = ElectionForm
    template_name = 'election_create.html'

    def get_form_kwargs(self):
        kwargs = super(ElectionCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        if self.object:
            return self.object.get_absolute_url()
        else:
            return reverse_lazy('elections:election_list')


class ConfigureElectionMixin(View):
    def dispatch(self, request, *args, **kwargs):
        self.election = get_object_or_404(Election, pk=kwargs.get('pk'))
        if self.election.user != self.request.user:
            raise Http404
        return super(ConfigureElectionMixin, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(ConfigureElectionMixin, self).get_form_kwargs()
        kwargs['election'] = self.election
        return kwargs

    def get_success_url(self):
        return reverse('elections:election_details', args=(self.election.pk,))


class ElectionDeleteView(ConfigureElectionMixin, DeleteView):
    model = Election
    template_name = 'election_delete.html'

    def get_success_url(self):
        return reverse('elections:election_list')


class ElectionDetailView(DetailView):
    model = Election
    template_name = 'election_details.html'
    context_object_name = 'election'

    def get_context_data(self, **kwargs):
        ctx = super(ElectionDetailView, self).get_context_data(**kwargs)
        if self.object.voters.count() <= 100:
            ctx['voters'] = self.object.voters.all().prefetch_related('preferences', 'preferences__candidate')
        ctx['results'] = self.object.results.all()\
            .select_related('geneticalgorithmsettings').prefetch_related('winners')
        choices = [(res.pk, str(res)) for res in ctx['results'].reverse()]
        choices.append((None, '------'))
        choices.reverse()
        ctx['results_choice'] = Select(choices=choices).render('results_choice', None)
        ctx['results_number'] = self.object.results.count()
        ctx['results_pks'] = ",".join([str(n) for n in self.object.results.values_list('pk', flat=True)])
        ctx['results_p_params'] = "," + ",".join(
            [str(n) for n in self.object.results.values_list('p_parameter', flat=True)]
        )
        ctx['results_descriptions'] = "No result," + ",".join(
            ['{}: p = {}'.format(r.get_algorithm_display(), r.p_parameter) for r in self.object.results.all()]
        )
        return ctx


class ElectionLoadDataFormView(ConfigureElectionMixin, FormView):
    form_class = ElectionLoadDataForm
    template_name = 'election_load_data.html'
    election = None

    def form_valid(self, form):
        file = form.cleaned_data['file']
        try:
            self.load_data_from_file(file)
        except Exception as exc:
            form.add_error('file', str(exc))
            return self.form_invalid(form)
        return super(ElectionLoadDataFormView, self).form_valid(form)

    def load_data_from_file(self, election_data):
        with transaction.atomic():
            voters_number_in_loop = 0

            candidates_number = int(election_data.readline())
            if candidates_number <= 0:
                raise IncorrectTypeOfCandidatesNumberException

            # reading candidates' names
            for i in xrange(candidates_number):
                line = election_data.readline()
                try:
                    candidate_name = line.split(',', 1)[1].strip()
                    candidate_id = line.split(',', 1)[0].strip()
                except IndexError:
                    raise CandidatesNameIncorrectFormatException(2 + i)
                Candidate.objects.create(
                    election=self.election,
                    name=candidate_name,
                    soc_id=candidate_id
                )

            # reading number of all votes and unique votes
            line = election_data.readline()
            line = line.split(',', 2)

            try:
                voters_number = int(line[1])
                unique_votes = int(line[2])
                check_votes_number_unique_votes_relation(voters_number, unique_votes)
            except IndexError:
                raise SummingLineFormatException(2 + candidates_number)
            except ValueError:
                raise SummingLineTypeException(2 + candidates_number)

            # reading order preferences
            for i in xrange(unique_votes):
                line = election_data.readline()
                if line == '':
                    raise BadDataFormatException
                line = line.split(',', candidates_number)
                try:
                    line = [int(x) for x in line]
                except ValueError:
                    raise PreferenceOrderTypeException(3 + candidates_number + i)
                if line[0] <= 0 or line[0] > voters_number:
                    raise PreferenceOrderLogicException(3 + candidates_number + i)
                voters_number_in_loop += line[0]
                check_vote_consistency(line[1:], candidates_number)
                # vote = Vote(line[0], line[1:])
                voter = Voter.objects.create(
                    election=self.election,
                    repeats=line[0]
                )
                voter.set_preferences_by_ids(line[1:])

            check_number_of_votes_consistency(voters_number, voters_number_in_loop)

            message = """
            <strong>Successfully added election data from file!</strong><br>
            * Candidates number: {}<br>
            * Voters number: {}<br>
            * Unique votes: {}<br>
            """
            messages.success(
                self.request,
                message.format(candidates_number, voters_number, unique_votes)
            )

        election_data.close()


class ElectionGenerateDataFormView(ConfigureElectionMixin, FormView):
    form_class = ElectionGenerateDataForm
    template_name = 'election_generate_data.html'
    election = None

    def form_valid(self, form):
        generator = ElectionGenerator(self.election, **form.cleaned_data)
        generator.generate_elections()
        return super(ElectionGenerateDataFormView, self).form_valid(form)


class ElectionPaintView(ConfigureElectionMixin, TemplateView):
    template_name = 'election_paint_data.html'
    election = None

    def dispatch(self, request, *args, **kwargs):
        self.election = get_object_or_404(Election, pk=kwargs.get('pk'))
        if self.election.user != self.request.user:
            raise Http404
        return super(ElectionPaintView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(ElectionPaintView, self).get_context_data(**kwargs)
        ctx['election'] = self.election
        ctx['MAX_CANDIDATES'] = settings.ELECTION_GENERATOR['MAX_CANDIDATES']
        ctx['MAX_VOTERS'] = settings.ELECTION_GENERATOR['MAX_VOTERS']
        return ctx

    def post(self, request, pk):
        data = json.loads(request.body)
        loader = ElectionPaintLoader(self.election, data['candidates'], data['voters'])
        loader.load_elections()
        return HttpResponse(reverse("elections:election_details", args=(self.election.pk,)))


class ElectionChartView(ChartMixin):
    datasets_number = 2
    labels = ['Candidates', 'Voters']
    colors = ['black', 'black']
    points_stroke_colors = ['green', 'blue']

    def dispatch(self, request, *args, **kwargs):
        try:
            self.election = Election.objects.get(pk=kwargs['pk'])
        except Election.DoesNotExist:
            raise Http404
        return super(ElectionChartView, self).dispatch(request, *args, **kwargs)

ecs/elections/templates/election_detail_view.html
{% extends 'base.html' %}

{% block title %}
    {{ election }}
{% endblock %}

{% block content %}
    committee size: {{ election.committee_size }}

{% endblock %}

ecs/elections/templates/election_details.html
{% extends 'base.html' %}

{% block title %}
    {{ election }}
{% endblock %}

{% block content %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message|safe }}</div>
    {% endfor %}

    <p>
        committee size: {{ election.committee_size }}
    </p>

    {% if election.is_generated and election.results.count %}
        <div id="results-slider-wrapper">
            <input id="results-slider"
                data-slider-id='results-slider' type="text"
                data-slider-min="0" data-slider-max="{{ results_number }}"
                data-slider-step="1" data-slider-value="0"
                data-results-pks="{{ results_pks }}"
                data-results-p-params="{{ results_p_params }}"
                data-results-descriptions="{{ results_descriptions }}"
            >
        </div>
    {% endif %}

    {% if not election.is_set_up %}
        <div class="alert alert-info">
            <span class="glyphicon glyphicon-info-sign"></span>
            You should add voters and candidates!
        </div>

        <div class="btn-group btn-group-lg btn-group-justified" role="group">
            <a href="{% url 'elections:election_load_data' election.pk %}" class="btn btn-info" role="button">
                <span class="glyphicon glyphicon-upload" style="font-size: 4em"></span><br>
                Load data from file (.soc PrefLib format)
            </a>
            <a href="{% url 'elections:election_generate' election.pk %}" class="btn btn-info" role="button">
                <span class="glyphicon glyphicon-equalizer" style="font-size: 4em"></span><br>
                Generate election from normal distribution
            </a>

            <a href="{% url 'elections:election_paint' election.pk %}" class="btn btn-info" role="button">
                <span class="glyphicon glyphicon-edit" style="font-size: 4em"></span><br>
                Draw chart
            </a>
        </div>
    {% else %}

        {% if election.is_generated %}

            <h2>Chart</h2>
            <div class="container">
                <div class="col-md-1"></div>
                <div class="col-md-9">
                    <canvas id="election_chart" data-url="{% url 'elections:chart_data' election.pk %}"
                            width="580" height="580"></canvas>
                </div>
                <div class="col-md-2"></div>
            </div>

        {% endif %}
        <h2>Algorithms comparison</h2>
        <div class="container">
            <div class="col-md-1"></div>
            <div class="col-md-9">
                <canvas id="algorithms_chart" data-url="{% url 'elections:algorithms_chart_data' election.pk %}"
                        width="580" height="580"></canvas>
            </div>
            <div class="col-md-2"></div>
        </div>

        <h2>Available results</h2>

        {% regroup results by p_parameter as p_list %}
        <div class="row"><div class="col-md-10 col-md-push-1">
        <table class="table">
            <thead class="bg-primary">
            <tr>
                <th class="col-md-1">p param</th>
                <th class="col-md-2">Algorithm</th>
                <th class="col-md-2">Time</th>
                <th class="col-md-2" data-toggle="tooltip" title="This value should be compared only between results with the same p parameter!">
                    Committee score <span class="glyphicon glyphicon-info-sign"></span>
                </th>
                <th class="col-md-3">Algorithm parameters</th>
                <th class="col-md-2">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% if not election.results.count %}
                <tr>
                    <td colspan="6" class="bg-info" style="text-align: center;">
                        No result avaiable. To add first result press button below!
                    </td>
                </tr>
            {% endif %}
            {% for results_group in p_list %}

                {% for result in results_group.list %}
                    <tr {% if forloop.parentloop.counter|divisibleby:2 %}class="bg-warning"{% endif %}>
                        <th style="text-align: center" scope="row">{{ result.p_parameter }}</th>
                        <td>{{ result.get_algorithm_display }}</td>
                        <td>
                            {% if result.winners.count %}
                                {{ result.time|floatformat:2 }} s
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td>
                            {% if result.winners.count %}
                                {{ result.score|floatformat:2 }}
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <td>
                            {% if result.geneticalgorithmsettings %}
                                <div class="algorithm-settings">
                                    <div class="algorithm-settings-single" data-toggle="tooltip" title="Cycles count">
                                        <i class="fa fa-repeat" aria-hidden="true"></i> {{ result.geneticalgorithmsettings.cycles }}
                                    </div>
                                    <div class="algorithm-settings-single" data-toggle="tooltip" title="Mutation probability in %">
                                        <i class="fa fa-code-fork" aria-hidden="true"></i> {{ result.geneticalgorithmsettings.mutation_probability }}
                                    </div>
                                    <div class="algorithm-settings-single" data-toggle="tooltip" title="Crossing probability in %">
                                        <i class="fa fa-venus-mars" aria-hidden="true"></i> {{ result.geneticalgorithmsettings.crossing_probability }}
                                    </div>
                                </div>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ result.get_absolute_url }}">
                                <button class="btn btn-info btn-xs">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </a>
                            <a href="{% url 'elections:result_delete' result.pk %}">
                                <button class="btn btn-danger btn-xs">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
        </div></div>


        <a href="{% url 'elections:result_create' election.pk %}">
            <button class="btn btn-success">
                Add new result
            </button>
        </a>

        {% if voters %}
            <h2>Voters listing</h2>
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#voters_panel">Collapse/expand voters listing</a>
                        </h4>
                    </div>
                    <div id="voters_panel" class="panel-collapse collapse">
                        {% for voter in voters %}
                            <div class="panel-body">
                                <strong>{{ voter.repeats }}</strong>x
                                {% for preference in voter.preferences.all %}
                                    {{ preference.preference }}&nbsp;-&nbsp;{{ preference.candidate }}&nbsp;[{{ preference.candidate.soc_id }}]{% if not forloop.last %},{% endif %}
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <div class="panel-footer">
                            <p>Listing format:<br>
                                <code>
                                    <strong>:vote_repeats:</strong> x :preference_index: - :candidate_name:
                                    [:candidate_id:],
                                    :preference_index: - :candidate_name: [:candidate_id:], …
                                </code>
                            </p>
                            <p>
                                Example:
                                <br>
                                <code>
                                    <strong>7</strong>x 1 - John Snow [2], 2 - Daenerys [1], 3 - Cersei [3]
                                </code><br>
                                means there are 7 voters that choose John Snow in the first place, Danearys the second
                                and
                                Cersei as the last candidate in their preference.
                                <br>
                                Daenerys has id 1 in database (John Snow has 2 and Cersei has 3).
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div style="margin-bottom: 50px"></div>
        {% endif %}
    {% endif %}

{% endblock %}

ecs/elections/templates/election_list.html
{% extends 'base.html' %}

{% block title %}
    Your elections
{% endblock %}

{% block content %}
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Candidates</th>
            <th>Voters</th>
            <th>Results</th>
            <th>Actions</th>
        </tr>
        {% for election in elections %}
            <tr>
                <td>
                    <a href="{{ election.get_absolute_url }}">
                        {{ election }}
                    </a>
                </td>
                <td>
                    {{ election.candidates.count }}
                </td>
                <td>
                    {{ election.voters.count }}
                </td>
                <td>
                    {{ election.results.count }}
                </td>
                <td>
                    <a href="{% url 'elections:election_delete' election.pk %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>

    <p style="float:right">
        <a href="{% url 'elections:election_create' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>
                New election
            </button>
        </a>
    </p>

{% endblock %}

ecs/elections/templates/election_paint_data.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Mark voters and candidates
{% endblock %}

{% block content %}
    <!--- threejs for paint -->
    {% csrf_token %}
    <div class="panel panel-primary">
        <div class="panel-body">
            <ul>
                <li>Press V to draw voters</li>
                <li>Press C to draw candidates</li>
                <li>Press +/- to change marker size</li>
            </ul>
        </div>
    </div>

    <div class="panel panel-primary">
        <canvas id="ecs-paint" width="810" height="810"></canvas>
        <div class="panel-footer">
            <div class="row">
                <div class="col-xs-offset-2 col-sm-2">
                    Candidates: <span id="candidates">0</span>/<span id="candidates_limit"></span>
                </div>
                <div class="col-sm-2">
                    Voters: <span id="voters">0</span>/<span id="voters_limit"></span>
                </div>
                <div class="col-sm-2">
                    Adding: <span id="mode"></span>
                </div>
                <div class="col-sm-1">
                    X: <span id="x_pos">0</span>
                </div>
                 <div class="col-sm-1">
                    Y: <span id="y_pos">0</span>
                </div>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary" onclick="getPaintedData(PAINT_VIEW)">Save and proceed
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script>
        var MAX_CANDIDATES = {{ MAX_CANDIDATES }};
        var MAX_VOTERS = {{ MAX_VOTERS }};
        var PAINT_VIEW = "{%  url 'elections:election_paint' election.pk %}"
    </script>

    <script>
        var csrftoken = "{{ csrf_token }}";
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>

    <script type="text/javascript" src="{% static 'three.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'ECSPaint.js' %}"></script>

{% endblock %}

ecs/elections/templates/result_details.html
{% extends 'base.html' %}

{% block title %}
    {{ result }}
{% endblock %}

{% block content %}

    {% if result.election.is_generated %}

        <h2>Chart</h2>
        <div class="container">
            <div class="col-md-1"></div>
            <div class="col-md-9">
                <canvas id="election_chart" data-url="{% url 'elections:result_chart_data' result.pk %}"
                        width="580" height="580"></canvas>
            </div>
            <div class="col-md-2"></div>
        </div>

    {% endif %}

    <h2>Winners</h2>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#results_panel">Collapse/expand winners listing</a>
                </h4>
            </div>
            <div id="results_panel" class="panel-collapse collapse in">
                {% for candidate in result.winners.all %}
                    <div class="panel-body">
                        <strong>{{ candidate }}</strong>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}